USE test;

CREATE TABLE users(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name TEXT NOT NULL,
	email TEXT NOT NULL,
	password TEXT NOT NULL
);
CREATE TABLE products(
	id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name TEXT NOT NULL,
	price DECIMAL(13,2) NOT NULL,
	user TEXT NOT NULL
);
